---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        name: [ sysstat, bc, gawk, coreutils, procps, jq ]
    - name: Ensure /opt/datashipper directory exists
      file:
        path: /opt/datashipper
        recurse: yes
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Install collect_cpu_usage.sh
      copy:
        src: collect_cpu_usage.sh
        dest: /opt/datashipper/collect_cpu_usage
        owner: root
        group: root
        mode: '0755'
    - name: Allow user to execute collect_cpu_usage without password
      lineinfile:
        dest: /etc/sudoers.d/collect_cpu_usage
        line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: /opt/datashipper/collect_cpu_usage"
        create: yes
        owner: root
        group: root
        mode: "0440"
        state: present
        validate: 'visudo -c -f %s'
    - name: Install collect_mem_usage.sh
      copy:
        src: collect_mem_usage.sh
        dest: /opt/datashipper/collect_mem_usage
        owner: root
        group: root
        mode: '0755'
    - name: Allow user to execute collect_mem_usage without password
      lineinfile:
        dest: /etc/sudoers.d/collect_mem_usage
        line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: /opt/datashipper/collect_mem_usage"
        create: yes
        owner: root
        group: root
        mode: "0440"
        state: present
        validate: 'visudo -c -f %s'
    - name: Install collect_disk_usage.sh
      copy:
        src: collect_disk_usage.sh
        dest: /opt/datashipper/collect_disk_usage
        owner: root
        group: root
        mode: '0755'
    - name: Allow user to execute collect_disk_usage without password
      lineinfile:
        dest: /etc/sudoers.d/collect_disk_usage
        line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: /opt/datashipper/collect_disk_usage"
        create: yes
        owner: root
        group: root
        mode: "0440"
        state: present
        validate: 'visudo -c -f %s'
