---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    # Collectors scripts
    - name: Install packages
      apt:
        update_cache: yes
        name: [ tshark, bc, gawk, procps ]
    - name: Ensure /opt/datashipper/output directory exists
      file:
        path: /opt/datashipper/output
        recurse: yes
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Ensure /opt/datashipper/configs directory exists
      file:
        path: /opt/datashipper/configs
        recurse: yes
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Install collect-data-rate.sh
      copy:
        src: collect-data-rate.sh
        dest: /opt/datashipper/collect-data-rate
        owner: root
        group: root
        mode: '0755'
    - name: Install collect-tcp-avg-rtt.sh
      copy:
        src: collect-tcp-avg-rtt.sh
        dest: /opt/datashipper/collect-tcp-avg-rtt
        owner: root
        group: root
        mode: '0755'
    # Filebeat
    - name: Install filebeat package
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.8.1-amd64.deb
    - name: Backup original filebeat configuration
      command: mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.bak
    - name: Copy new filebeat configuration (no inputs)
      copy:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
    - name: Restart filebeat service
      systemd:
        state: restarted
        daemon_reload: yes
        name: filebeat
