---
- hosts: all
  remote_user: ubuntu
  become: yes
  vars:
    datashipper_user: datashipper
    datashipper_password: your-hashed-password

  tasks:
    - name: Ensure /opt/datashipper/output directory exists
      file:
        path: /opt/datashipper/output
        recurse: yes
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Ensure /opt/datashipper/configs directory exists
      file:
        path: /opt/datashipper/configs
        recurse: yes
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Install filebeat package
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.8.1-amd64.deb
    - name: Backup original filebeat configuration
      command: mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.bak
    - name: Copy new filebeat configuration
      copy:
        src: filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
    - name: Restart filebeat service
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: filebeat
    - name: Install add_input_config.sh to manage inputs
      copy:
        src: add_input_config.sh
        dest: /opt/datashipper/add_input_config
        owner: root
        group: root
        mode: '0755'
    - name: Ensure datashipper_user exists
      user:
        state: present
        name: "{{ datashipper_user }}"
        password: "{{ datashipper_password }}"
        groups: sudo
        create_home: no
        shell: /bin/bash
    - name: Allow datashipper_user to execute add_input_config without password
      lineinfile:
        dest: /etc/sudoers.d/add_input_config
        line: "{{ datashipper_user }} ALL=(ALL) NOPASSWD: /opt/datashipper/add_input_config"
        create: yes
        owner: root
        group: root
        mode: "0440"
        state: present
        validate: 'visudo -c -f %s'
